### ISSUE TITLE
Code clean up

### ISSUE THREAD

**Issue by eduardokraus** [bdaloukas/moodle-mod_mmogame#1]
Hello,
please review and clean up your code, and remove unused variables, DB calls, etc.

![Captura de Tela 2024-10-24 às 11 28 15](https://github.com/user-attachments/assets/e5bedfb7-ccab-4b67-b611-8dc417b4ab63)

**Comment by eduardokraus** [comment]
https://github.com/bdaloukas/moodle-mod_mmogame/blob/main/db/upgrade.php#L48

**Comment by bdaloukas** [comment]
Done.
