### ISSUE TITLE
Potential performance issues

### ISSUE THREAD

**Issue by volodymyrdovhan** [bdaloukas/moodle-mod_mmogame#12]
Hello,

I noticed that your plugin contains several nested database queries within loops. This approach can negatively impact performance.

I recommend reviewing your plugin's logic to extract data from the database in bulk. You can use various SQL techniques, such as using OR with conditions and retrieving data using IN (sequence) or IN (subquery), to fetch specific data in bulk with minimum queries to DB.

By optimizing your database calls, you can significantly improve the plugin's performance.

Thank you.

![image](https://github.com/user-attachments/assets/f0ac548d-b6f8-4e75-a0d4-639922fb894b)
![image](https://github.com/user-attachments/assets/9b473990-f622-4702-b5a3-6c080c920ddb)
![image](https://github.com/user-attachments/assets/3b5afbc0-a360-43d7-b7b2-4608f4b00506)

**Comment by bdaloukas** [comment]
Fixed.
