### ISSUE TITLE
Hardcoded parameters in SQL queries and DB prefix usage

### ISSUE THREAD

**Issue by volodymyrdovhan** [bdaloukas/moodle-mod_mmogame#13]
Hello,
1. I found hardcoded parameters in SQL queries, which should be implemented as placeholders:
https://moodledev.io/docs/5.0/apis/core/dml#placeholders

2. In addition, it is not a common way to use prefix config param hardcoded in the SQL query - you need to use curly braces in SQL queries which will be automatically replaced with table name and prefix: https://moodledev.io/docs/5.0/apis/core/dml#table-prefix

3. Use SQL get_in_or_equal() method to utilise IN operator:
https://moodledev.io/docs/5.0/apis/core/dml#get_in_or_equal

Please review the documentation:

- [SQL coding style](https://moodledev.io/general/development/policies/codingstyle/sql)
- [Data manipulation API](https://moodledev.io/docs/5.0/apis/core/dml)

![image](https://github.com/user-attachments/assets/e70b32c6-2ba8-4835-9204-d970457e3ce5)
![image](https://github.com/user-attachments/assets/b166b4ec-9360-4437-99b8-3c108785f75f)
![image](https://github.com/user-attachments/assets/56892151-bf39-4ce9-8a0b-fa01c37cbaff)
![image](https://github.com/user-attachments/assets/a2c3500d-76bb-488f-99f3-7e4c7254480e)
![image](https://github.com/user-attachments/assets/244dcd3e-03a8-4a46-874e-2d88ba48a90a)
![image](https://github.com/user-attachments/assets/dbcdb6f0-0f5d-4d42-b8cf-f5f863ee8b64)
![image](https://github.com/user-attachments/assets/bfee4b3c-f662-4bf4-8081-d7a780868760)

**Comment by bdaloukas** [comment]
Removed usage of $DB->prefix

**Comment by bdaloukas** [comment]
Done
