### ISSUE TITLE
Not fully implemented Privacy Provider

### ISSUE THREAD

**Issue by volodymyrdovhan** [bdaloukas/moodle-mod_mmogame#16]
Hello,
I found some Privacy Provider API methods are not implemented.
Please implement all required methods for Privacy API.

You can validate the implementation with CLI Tools:
https://moodledev.io/docs/4.5/apis/subsystems/privacy/utils

![image](https://github.com/user-attachments/assets/d7c4d48d-99e9-4501-9be1-f7852015df49)

**Comment by bdaloukas** [comment]
Function delete_data_for_users it is necesary for interface core_userlist_provider.
Add comments. There is nothing to delete.
