### ISSUE TITLE
Missing Header and Copyright Information in Files

### ISSUE THREAD

**Issue by volodymyrdovhan** [bdaloukas/moodle-mod_mmogame#20]
Hello,
I noticed that the JS files are missing the correct header and copyright/author notes. According to the[ Moodle Plugin Contribution Checklist](https://moodledev.io/general/community/plugincontribution/checklist#boilerplate), all files should include the common boilerplate header with an explicit GPL license statement at the beginning.
Please review and update the plugin accordingly.

![image](https://github.com/user-attachments/assets/9d11086f-c584-407a-a8cc-cec301252b7d)
![image](https://github.com/user-attachments/assets/08e39f1e-e77e-4676-ad8b-e40d5eddcaa2)

**Comment by bdaloukas** [comment]
Done
