### ISSUE TITLE
Moodle classes autoloading utilisation

### ISSUE THREAD

**Issue by volodymyrdovhan** [bdaloukas/moodle-mod_mmogame#23]
Hello,
please consider using Moodle classes autoloading for plugin custom classes: https://docs.moodle.org/dev/Automatic_class_loading

You need to put files in '/classes/local' folder, and give the correct name and the namespace - and Moodle will automatically load these classes and you don't need to require these files manually.

![image](https://github.com/user-attachments/assets/77a25dcd-09bf-43db-bcbe-ecfb20cd54a6)

**Comment by bdaloukas** [comment]
Done.
