### ISSUE TITLE
Direct access of $_POST

### ISSUE THREAD

**Issue by eduardokraus** [bdaloukas/moodle-mod_mmogame#4]
https://github.com/bdaloukas/moodle-mod_mmogame/blob/main/state.php#L25

**Comment by bdaloukas** [comment]
The file state.php doesn't use the lib of Moodle because it is need to work very quickly.
Just reads a file at $CFG->dataroot."/temp/mmogame/states/{$fastjson}/{$fastjson}.txt" and outputs the containts.
It is used to check if has changed the state of game.
