### ISSUE TITLE
DB error when tried to play the game

### ISSUE THREAD

**Issue by volodymyrdovhan** [bdaloukas/moodle-mod_mmogame#6]
Hello,
I got an error when tried to play a game:
![image](https://github.com/user-attachments/assets/6360556c-301d-4729-bd57-1ae54dfd024f)

I'm using Postgre DB.

**Full Error:**
{
    "error": "Error reading from database",
    "errorcode": "dmlreadexception",
    "stacktrace": "* line 494 of \/lib\/dml\/moodle_database.php: dml_read_exception thrown\n* line 293 of \/lib\/dml\/moodle_read_slave_trait.php: call to moodle_database->query_end()\n* line 358 of \/lib\/dml\/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->read_slave_query_end()\n* line 1044 of \/lib\/dml\/pgsql_native_moodle_database.php: call to pgsql_native_moodle_database->query_end()\n* line 1684 of \/lib\/dml\/moodle_database.php: call to pgsql_native_moodle_database->get_records_sql()\n* line 1656 of \/lib\/dml\/moodle_database.php: call to moodle_database->get_record_sql()\n* line 117 of \/mod\/mmogame\/database\/moodle.php: call to moodle_database->get_record_select()\n* line 446 of \/mod\/mmogame\/mmogame.php: call to mmogame_database_moodle->get_record_select()\n* line 493 of \/mod\/mmogame\/mmogame.php: call to mmogame->get_grade()\n* line 105 of \/mod\/mmogame\/json.php: call to mmogame->get_avatar_info()\n* line 54 of \/mod\/mmogame\/json.php: call to dogetavatars()\n",
    "debuginfo": "ERROR:  column \"Game Design\" does not exist\nLINE 1: ...id FROM m_mmogame_aa_colorpalettes WHERE category=\"Game Desi...\n                                                             ^\nSELECT id as minid FROM m_mmogame_aa_colorpalettes WHERE category=\"Game Design\" AND name=\"Valheim \/ UI Redesign\"\n[array (\n)]\nError code: dmlreadexception",
    "reproductionlink": "https:\/\/moodle.local:445\/moodle\/mod\/mmogame\/gate.php?id=1&pin=510316"
}

**Comment by bdaloukas** [comment]
It is fixed.
