### ISSUE TITLE
Undefined variables and functions in multiple files

### ISSUE THREAD

**Issue by volodymyrdovhan** [bdaloukas/moodle-mod_mmogame#7]
Hello,
I found a lot of undefined variables and functions in multiple files and places.
Please review the code and fix all issues, as it may break the plugin functionality.

![image](https://github.com/user-attachments/assets/1aeee975-296d-4308-b86f-f0c3df31366c)
![image](https://github.com/user-attachments/assets/08ef7b34-1bad-4ede-a021-57add92c39ec)
![image](https://github.com/user-attachments/assets/78e964bf-f5b9-4f45-aa26-dd2ff6ce9e89)
![image](https://github.com/user-attachments/assets/7dfacb2e-af55-4266-866b-028314c6f3c5)
![image](https://github.com/user-attachments/assets/1d821b5b-4668-4c1a-808b-a0ea36dbcd9a)
![image](https://github.com/user-attachments/assets/612e3c5a-c3c2-4161-93cd-1c34ff232ceb)
![image](https://github.com/user-attachments/assets/c04945c8-d0fa-4436-91e8-e20f800ca0a0)
![image](https://github.com/user-attachments/assets/59330ead-0e5b-4903-a29a-d00d377a5438)
![image](https://github.com/user-attachments/assets/ecae6ef6-606e-435c-b8d2-7a1bfbcfa22c)
![image](https://github.com/user-attachments/assets/3470a497-c27c-4747-9034-0539321ec40f)
![image](https://github.com/user-attachments/assets/5c1a0a51-683c-4037-a453-7f05cb0a5b81)
![image](https://github.com/user-attachments/assets/f17a1492-aed3-44e0-895a-90bdcd80c7df)
![image](https://github.com/user-attachments/assets/1e70f14d-6c2c-4cde-8197-f7c029e971d1)
![image](https://github.com/user-attachments/assets/541badb1-eaa0-4017-8246-2f89e17816c5)

**Comment by bdaloukas** [comment]
Finished phase 1

**Comment by bdaloukas** [comment]
Finished.
